### ISSUE TITLE
Not usable on Windows

### ISSUE THREAD

**Issue by abstrus** [rubik/xenon#12]
Since `xenon` depends on `sh`, it will not work on Windows (see [sh](https://github.com/NiranjanaD/sh)).

If not fixed, maybe this could be documented ?

**Comment by rubik** [comment]
Good point. sh is really just used in `xenon/repository.py`, so I'll replace it with subprocess. I just used it for the convenience it offered.

**Comment by abstrus** [comment]
Much appreciated, my contributors under windows will be grateful!

**Comment by rubik** [comment]
I published xenon 0.3.4 on PyPI, please check it out.
