### ISSUE TITLE
Update PyYAML requirement to allow 3.12

### ISSUE THREAD

**Issue by dougthor42** [rubik/xenon#16]
PyYAML 3.11 fails compilation during `pip install`. If `xenon` allowed PyYaml 3.12, which [added Windows wheels](http://pyyaml.org/wiki/PyYAML#History) for Py27, 34, and 35, then Windows users would be super happy :-)

**Comment by rubik** [comment]
Great, thanks for the heads up!

**Comment by rubik** [comment]
I pushed version 0.5.1 to PyPI.
