### ISSUE TITLE
LICENSE file not included in the pip source package

### ISSUE THREAD

**Issue by igortg** [rubik/xenon#20]
LICENSE file is not present in the pip tar.gz file. Would be nice to have it on the package to comply with MIT license.

**Comment by rubik** [comment]
Hi Igor, thanks for pointing it out!
I've updated the `MANIFEST.in` file and pushed a new release to PyPI (`v0.5.4`).

**Comment by igortg** [comment]
Thks man. Just to let you know that I made `xenon` and it's dependencies available on https://conda-forge.org

The guys out there that complained about the missing LICENSE file.

**Comment by rubik** [comment]
I see. Thanks a lot for your work, I really appreciate it!
