### ISSUE TITLE
Version resolution miss-match

### ISSUE THREAD

**Issue by sobolevn** [rubik/xenon#24]
While working on a project that uses secure version of `pyyaml` I have failed to install `xenon` with `poetry`, because these packages rely on different library versions:

```
Because no versions of layer-linter match >0.12.0,<0.13.0
 and layer-linter (0.12.0) depends on PyYAML (>=4.2b1,<5.0.0), layer-linter (>=0.1
2.0,<0.13.0) requires PyYAML (>=4.2b1,<5.0.0).
Thus, layer-linter (>=0.12.0,<0.13.0) is incompatible with xenon (>=0.5,<0.6).
So, because kira depends on both xenon (^0.5) and layer-linter (^0.12.0), version
solving failed.
```

Steps:

1. `poetry init` - to create a new project
2. `poetry add xenon`
3. `poetry add layer-lint`

**Comment by rubik** [comment]
Thanks for the heads up! I have updated the version requirements for PyYAML and I uploaded xenon v0.5.5 to PyPI!

**Comment by sobolevn** [comment]
@rubik awesome, thanks!
