### ISSUE TITLE
PyYaml version req is not available in pip

### ISSUE THREAD

**Issue by alicon** [rubik/xenon#25]
<img width="170" alt="screen shot 2019-02-05 at 3 53 27 pm" src="https://user-images.githubusercontent.com/4838093/52309699-35ee8700-295e-11e9-9b04-3f5bdb5a72a6.png">

**Comment by alicon** [comment]
<img width="458" alt="screen shot 2019-02-05 at 3 54 11 pm" src="https://user-images.githubusercontent.com/4838093/52309736-4dc60b00-295e-11e9-8a5a-ece0f395be99.png">

**Comment by alicon** [comment]
This causes Xenon's dependency list to be unsatisfiable.

**Comment by alicon** [comment]
<img width="1212" alt="screen shot 2019-02-05 at 3 55 34 pm" src="https://user-images.githubusercontent.com/4838093/52309817-8239c700-295e-11e9-8d23-88696a7f99ca.png">

**Comment by alicon** [comment]
It is however available via github:

<img width="372" alt="screen shot 2019-02-05 at 3 56 12 pm" src="https://user-images.githubusercontent.com/4838093/52309848-9b427800-295e-11e9-8906-caa0ccccc37a.png">

**Comment by rubik** [comment]
@alicon Earlier versions of PyYAML contain security issues. The next version is close to a release status. Check https://github.com/yaml/pyyaml/issues/193 for an update.

**Comment by herberthamaral** [comment]
@rubik sure thing, but that makes it impossible to install the latest version...

**Comment by oliparcol** [comment]
Given the changelog of the `5.1` version (https://github.com/yaml/pyyaml/blob/master/CHANGES) could you update the version specifier to something like `PyYAML>=4.2b1,<6.0` ?

Thanks

**Comment by rubik** [comment]
This was done but the issue wasn't closed. Closing now.
