### ISSUE TITLE
Flake8 plugin

### ISSUE THREAD

**Issue by sobolevn** [rubik/xenon#29]
Hi! Thanks for this awesome package.

I guess that user-base can be extended if you create a `flake8` plugin for `xenon`.
So, here's how the final usage will look like:

1. `pip install flake8 xenon`
2. `flake8 .` (runs both `flake8` and `xenon`)

**Comment by rubik** [comment]
Hi @sobolevn. Xenon is just a thin wrapper around Radon. In my mind, Xenon is just a tool to validate your complexity constraints, while Radon is a full-fledged analysis tool. Radon already has a Flake8 plugin, does it work for your needs?

https://github.com/rubik/radon/blob/master/radon/complexity.py#L110

**Comment by sobolevn** [comment]
Yeap, this works for me. 

Btw, `radon` is now a part of `wemake_python_styleguide` project: https://github.com/wemake-services/wemake-python-styleguide 🎉 

Thanks for building it!

**Comment by rubik** [comment]
@sobolevn That's great! Thanks for letting me know!
