### ISSUE TITLE
Read configuration from `setup.cfg`

### ISSUE THREAD

**Issue by sobolevn** [rubik/xenon#31]
My list of ignore and exclude options grew quite big, together with `--max-absolute B --max-modules A --max-average A` it looks to verbose to use.

Is it an option to specify the configuration inside `setup.cfg` (default place for configuring python tools like flake8, mypy, isort, etc)?

**Comment by rubik** [comment]
Currently that is not supported. It was also requested for radon. I will have some time in 2/3 weeks so I might take a stab at that then.

**Comment by sobolevn** [comment]
Awesome! Thanks.

**Comment by rubik** [comment]
Given that I never got around to implementing this, and `setup.cfg` is now considered more of a legacy approach, I'm closing this issue.
