### ISSUE TITLE
PypI release

### ISSUE THREAD

**Issue by evstratbg** [rubik/xenon#32]
Hi! I use pipenv and I have constant problems with locking dependencies, because the xenon requirements is yaml, <5.0, and everything below is in beta. An update to pypi would allow not to lock pre-release dependecies

**Comment by rubik** [comment]
Thanks for the heads up. We required <5.0 because there was a security issue in the first releases in the 5.x series. Now we can up the dependencies. I have released xenon 0.6.0 to PyPI. This new release also requires the newer Radon version.
