### ISSUE TITLE
PyYAML version preventing installation

### ISSUE THREAD

**Issue by commentator8** [rubik/xenon#45]
Hi,

I see that this has come up in the past and I was hoping it would be possible to again update the PyYAML dependency.
My project depends on PyYAML version 6 and xenon is <6.0.

```
Using version ^0.8.0 for xenon

Updating dependencies
Resolving dependencies... (3.8s)

  SolverProblemError

  Because no versions of xenon match >0.8.0,<0.9.0
   and xenon (0.8.0) depends on PyYAML (>=4.2b1,<6.0), xenon (>=0.8.0,<0.9.0) requires PyYAML (>=4.2b1,<6.0).
  So, because x-service depends on both PyYAML (6.0) and xenon (^0.8.0), version solving failed.
```

Thanks

**Comment by Hultner** [comment]
I also have problems with this, I'm stuck when it comes to updating a lot of our dependencies due to them explicitly depending on PyYAML >= 6 while xenon requires strictly under 6.

Is xenon strictly incompatible with PyYAML 6 or is it just that no new release have been done since the update?

**Comment by rubik** [comment]
@commentator8 @Hultner Thanks for bringing this issue to my attention. I widened the requirements to allow PyYAML version 6 in xenon v0.9.0. I just published it to PyPI.
