### ISSUE TITLE
Feature request - option to change log format for more convenient usage with PyCharm Terminal

### ISSUE THREAD

**Issue by izikeros** [rubik/xenon#49]
The PyCharm terminal has a feature that if the line starts with the path to the file and code line, it is replaced with a link, and when clicked, the user is moved to that location. This property of the terminal is very useful when using various linters that return the location of violation of some rules.

Would it be possible to e.g. add an option that will change the default log format to one without log level, module and change the log message format - remove quotes around the path?

CURRENT:
```
ERROR:xenon:block "jaba/core/engine.py:53 get_info" has a rank of C
ERROR:xenon:block "jaba/scripts/monitor.py:26 display_dashboard" has a rank of C
```

(desired) PyCharm Friendly:
```
jaba/core/engine.py:53 get_info has a rank of C
jaba/scripts/monitor.py:26 display_dashboard has a rank of C
```

**Comment by rubik** [comment]
Thanks, implemented in #56 with a few changes from your original PR.
