### ISSUE TITLE
What does xenon do?

### ISSUE THREAD

**Issue by fepegar** [rubik/xenon#55]
Hi! Thanks for this nice library. I have two simple questions:

1. Why would one use Xenon instead of Radon?
2. Does Xenon measure only cyclomatic complexity? It doesn't seem to mention the other metrics measured by Radon in the documentation.

**Comment by rubik** [comment]
Hi Fernando. Xenon is meant to be a thin wrapper around radon to be used in CI pipelines. It makes sure the codebase remains under specific complexity thresholds and fails otherwise. Currently Xenon only supports cyclomatic complexity, correct. Radon is meant manual usage and offers more checks.

**Comment by fepegar** [comment]
Thank you, @rubik!
