### ISSUE TITLE
Implement config file capability

### ISSUE THREAD

**Issue by rubik** [rubik/xenon#7]
It is among the command line options, but it does not work yet.

**Comment by Kristinita** [comment]
### 1. Documentation request

@rubik, please can you add to the Xenon documentation example configuration file? [**GitHub doesn’t have a single `.xenon.yml` file**](https://github.com/search?q=path%3A**%2F.xenon.yml&type=code). If configuring Xenon via the configuration file works, users may not intuitively understand what they should do.

### 2. MCVE

For example, I have any file `kira_file_with_bad_complexity.py` with a bad complexity.

Xenon successfully works for me with command-line arguments:

```shell
xenon kira_file_with_bad_complexity.py --max-average B
ERROR:xenon:average complexity is ranked C
```

I tried to set `max-average` in the file `.xenon.yml`:

```yaml
max-average: B

```

I run a command:

```shell
xenon kira_file_with_bad_complexity.py --config-file .xenon.yml
```

No effect. Xenon doesn’t return `ERROR:xenon:average complexity is ranked C`.

This file `.xenon.yml` also has no effect:

```yaml
max_average: B

```

Thanks.
